# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KlineLtcDay',
            fields=[
                ('time', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('amount', models.IntegerField()),
                ('count', models.IntegerField()),
                ('vol', models.FloatField()),
            ],
            options={
                'db_table': 'data_ltc_day',
            },
        ),
        migrations.CreateModel(
            name='KlineLtcHour',
            fields=[
                ('time', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('amount', models.IntegerField()),
                ('count', models.IntegerField()),
                ('vol', models.FloatField()),
            ],
            options={
                'db_table': 'data_ltc_hour',
            },
        ),
        migrations.CreateModel(
            name='KlineLtcMin15',
            fields=[
                ('time', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('amount', models.IntegerField()),
                ('count', models.IntegerField()),
                ('vol', models.FloatField()),
            ],
            options={
                'db_table': 'data_ltc_min15',
            },
        ),
        migrations.CreateModel(
            name='KlineLtcMin30',
            fields=[
                ('time', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('amount', models.IntegerField()),
                ('count', models.IntegerField()),
                ('vol', models.FloatField()),
            ],
            options={
                'db_table': 'data_ltc_min30',
            },
        ),
        migrations.CreateModel(
            name='KlineLtcMin5',
            fields=[
                ('time', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('amount', models.IntegerField()),
                ('count', models.IntegerField()),
                ('vol', models.FloatField()),
            ],
            options={
                'db_table': 'data_ltc_min5',
            },
        ),
        migrations.CreateModel(
            name='KlineLtcMonth',
            fields=[
                ('time', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('amount', models.IntegerField()),
                ('count', models.IntegerField()),
                ('vol', models.FloatField()),
            ],
            options={
                'db_table': 'data_ltc_month',
            },
        ),
        migrations.CreateModel(
            name='KlineLtcWeek',
            fields=[
                ('time', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('amount', models.IntegerField()),
                ('count', models.IntegerField()),
                ('vol', models.FloatField()),
            ],
            options={
                'db_table': 'data_ltc_week',
            },
        ),
    ]
