# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touzi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KlineBtcDay',
            fields=[
                ('time', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('amount', models.IntegerField()),
                ('count', models.IntegerField()),
                ('vol', models.FloatField()),
            ],
            options={
                'db_table': 'data_btc_day',
            },
        ),
        migrations.CreateModel(
            name='KlineBtcHour',
            fields=[
                ('time', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('amount', models.IntegerField()),
                ('count', models.IntegerField()),
                ('vol', models.FloatField()),
            ],
            options={
                'db_table': 'data_btc_hour',
            },
        ),
        migrations.CreateModel(
            name='KlineBtcMin15',
            fields=[
                ('time', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('amount', models.IntegerField()),
                ('count', models.IntegerField()),
                ('vol', models.FloatField()),
            ],
            options={
                'db_table': 'data_btc_min15',
            },
        ),
        migrations.CreateModel(
            name='KlineBtcMin30',
            fields=[
                ('time', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('amount', models.IntegerField()),
                ('count', models.IntegerField()),
                ('vol', models.FloatField()),
            ],
            options={
                'db_table': 'data_btc_min30',
            },
        ),
        migrations.CreateModel(
            name='KlineBtcMin5',
            fields=[
                ('time', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('amount', models.IntegerField()),
                ('count', models.IntegerField()),
                ('vol', models.FloatField()),
            ],
            options={
                'db_table': 'data_btc_min5',
            },
        ),
        migrations.CreateModel(
            name='KlineBtcWeek',
            fields=[
                ('time', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('amount', models.IntegerField()),
                ('count', models.IntegerField()),
                ('vol', models.FloatField()),
            ],
            options={
                'db_table': 'data_btc_week',
            },
        ),
        migrations.CreateModel(
            name='KlineBtcMonth',
            fields=[
                ('time', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('amount', models.IntegerField()),
                ('count', models.IntegerField()),
                ('vol', models.FloatField()),
            ],
            options={
                'db_table': 'data_btc_month',
            },
        ),
    ]
