# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touzi', '0002_klinebtcday_klinebtchour_klinebtcmin15_klinebtcmin30_klinebtcmin5_klinebtcweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klinebtcday',
            name='time',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='klinebtcmonth',
            name='time',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='klinebtcweek',
            name='time',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
